# Generated by Django 3.1.2 on 2021-06-29 22:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210629_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('geopandas', 'GeoPandas'), ('pandana', 'Pandana'), ('sklearn', 'Scikit-Learn'), ('dash', 'Plotly Dash'), ('osmnx', 'OSMnx'), ('qgis', 'QGIS'), ('python', 'Python'), ('sql', 'SQL')], default=('python', 'Python'), max_length=52),
        ),
    ]
