# Generated by Django 3.1.2 on 2021-06-30 00:05

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210630_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rendered_description',
            field=markdownfield.models.RenderedMarkdownField(default='Lorem ipsum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markdownfield.models.MarkdownField(rendered_field='rendered_description'),
        ),
    ]
