# Generated by Django 3.1.2 on 2021-06-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210630_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='rendered_description',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
    ]
