# Generated by Django 3.1.2 on 2021-07-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210701_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.URLField(default='https://github.com/nicholas-martino'),
        ),
    ]
