# Generated by Django 3.1.2 on 2021-07-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detailed_description',
            field=models.TextField(null=True),
        ),
    ]
