# Generated by Django 3.1.2 on 2021-07-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
