# Generated by Django 3.1.2 on 2021-07-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20210701_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='filter',
            field=models.TextField(default='filter-app'),
        ),
    ]
