# Generated by Django 3.1.2 on 2021-07-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210703_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='filter',
            field=models.CharField(default='filter-app', max_length=30),
        ),
    ]
