# Generated by Django 3.1.2 on 2021-07-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20210703_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('institution', models.TextField()),
                ('description', models.TextField()),
                ('hours', models.IntegerField()),
                ('education', models.BooleanField(default=False)),
            ],
        ),
    ]
