# Generated by Django 3.1.2 on 2021-07-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
