# Generated by Django 3.1.2 on 2021-07-05 20:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20210705_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('qgis', 'QGIS'), ('python', 'Python'), ('sql', 'SQL'), ('grasshopper', 'Grasshopper'), ('vray', 'V-Ray'), ('lumion', 'Lumion'), ('sketchup', 'SketchUp'), ('csharp', 'C#'), ('illustrator', 'Illustrator'), ('photoshop', 'Photoshop'), ('indesign', 'InDesign')], default=('python', 'Python'), max_length=86),
        ),
    ]
