# Generated by Django 3.1.2 on 2021-07-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20210705_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='filter',
            field=models.CharField(default='filter-cd', max_length=30),
        ),
    ]
