# Generated by Django 3.1.2 on 2021-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_project_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.URLField(blank=True, null=True),
        ),
    ]
