# Generated by Django 3.1.2 on 2021-11-20 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bottom_row',
        ),
    ]
