# Generated by Django 3.1.2 on 2022-03-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20211217_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='model',
            field=models.URLField(null=True),
        ),
    ]
