# Generated by Django 3.1.2 on 2021-07-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_auto_20210705_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
