# Generated by Django 3.1.2 on 2021-07-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0004_auto_20210705_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
