# Generated by Django 3.1.2 on 2021-07-05 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0005_auto_20210705_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 18, 54, 15, 101402)),
        ),
    ]
