# Generated by Django 3.1.2 on 2021-07-05 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0014_auto_20210705_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 20, 3, 15, 190199)),
        ),
    ]
