# Generated by Django 3.1.2 on 2021-07-06 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0017_auto_20210706_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 20, 50, 41, 237456)),
        ),
    ]
