# Generated by Django 3.1.2 on 2021-07-08 01:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0018_auto_20210706_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 8, 1, 57, 19, 798201, tzinfo=utc)),
        ),
    ]
